### ISSUE TITLE
Project Controller

### ISSUE THREAD

**Issue by b3j0f** [datapio/opencore#20]
- [ ] Implement ``sources/project-controller`` (see [MetaController](https://metacontroller.app))
    - [ ] Watch ``Project`` resources
    - [ ] Create ``Namespace`` named ``datapio-${userid}-${projectid}`` with annotation ``app.datap.io/kind: Project``
 - [ ] Helm chart in ``charts/system/project-controller``

**Comment by linkdd** [comment]
Implemented in #28
